/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mavenproject1;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author maxto3161
 */
public class InformacionP extends javax.swing.JFrame {

    private JTextField nameField, emailField, phoneField, addressField;
    private JButton saveButton, changePasswordButton;
    private JLabel messageLabel;

    /**
     * Creates new form InformacionP
     */
    public InformacionP() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
        setTitle("Actualizar Información");
        setSize(400, 300);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new GridBagLayout());
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.insets = new Insets(5, 5, 5, 5);
        gbc.fill = GridBagConstraints.HORIZONTAL;

        // Nombre
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.gridwidth = 1;
        getContentPane().add(new JLabel("Nombre:"), gbc);

        nameField = new JTextField(20);
        gbc.gridx = 1;
        gbc.gridy = 1;
        getContentPane().add(nameField, gbc);

        // Email
        gbc.gridx = 0;
        gbc.gridy = 2;
        getContentPane().add(new JLabel("Email:"), gbc);

        emailField = new JTextField(20);
        gbc.gridx = 1;
        gbc.gridy = 2;
        getContentPane().add(emailField, gbc);

        // Teléfono
        gbc.gridx = 0;
        gbc.gridy = 3;
        getContentPane().add(new JLabel("Teléfono:"), gbc);

        phoneField = new JTextField(20);
        gbc.gridx = 1;
        gbc.gridy = 3;
        getContentPane().add(phoneField, gbc);

        // Dirección
        gbc.gridx = 0;
        gbc.gridy = 4;
        getContentPane().add(new JLabel("Dirección:"), gbc);

        addressField = new JTextField(20);
        gbc.gridx = 1;
        gbc.gridy = 4;
        getContentPane().add(addressField, gbc);

        // Botón Guardar Cambios
        saveButton = new JButton("Guardar Cambios");
        gbc.gridx = 0;
        gbc.gridy = 5;
        gbc.gridwidth = 2;
        getContentPane().add(saveButton, gbc);

        // Botón Cambiar Contraseña
        changePasswordButton = new JButton("Cambiar Contraseña");
        gbc.gridx = 0;
        gbc.gridy = 6;
        gbc.gridwidth = 2;
        getContentPane().add(changePasswordButton, gbc);

        // Etiqueta de mensaje
        messageLabel = new JLabel("");
        messageLabel.setForeground(Color.GREEN);
        gbc.gridx = 0;
        gbc.gridy = 7;
        gbc.gridwidth = 2;
        getContentPane().add(messageLabel, gbc);

        saveButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (validateFields()) {
                    messageLabel.setText("Cambios guardados exitosamente!");
                    messageLabel.setForeground(Color.GREEN);
                } else {
                    messageLabel.setText("Por favor, complete todos los campos correctamente.");
                    messageLabel.setForeground(Color.RED);
                }
            }
        });

        changePasswordButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                JOptionPane.showMessageDialog(InformacionP.this, "Funcionalidad de cambio de contraseña no implementada", "Aviso", JOptionPane.INFORMATION_MESSAGE);
            }
        });

        pack();
    }// </editor-fold>                        

    private boolean validateFields() {
        return !nameField.getText().trim().isEmpty() &&
               !emailField.getText().trim().isEmpty() &&
               !phoneField.getText().trim().isEmpty() &&
               !addressField.getText().trim().isEmpty() &&
               emailField.getText().contains("@");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InformacionP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InformacionP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InformacionP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InformacionP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InformacionP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    // End of variables declaration                   
}
