/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mavenproject1;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author maxto3161
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
        setTitle("Hojas Secas - Panel Principal");
        setSize(600, 400);
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new BorderLayout());

        // Panel superior con información general
        JPanel topPanel = new JPanel(new GridLayout(2, 2));
        topPanel.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));
        topPanel.add(new JLabel("Propiedades Activas: 5"));
        topPanel.add(new JLabel("Propiedades Desocupadas: 2"));
        topPanel.add(new JLabel("Saldo Total: $1200"));
        getContentPane().add(topPanel, BorderLayout.NORTH);

        // Panel central con botones de acción
        JPanel centerPanel = new JPanel(new GridLayout(3, 2, 10, 10));
        centerPanel.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));

        String[] buttonLabels = {
            "Pagar Administración",
            "Reservar Espacio Común",
            "Ver Facturas",
            "Ver Multas",
            "Actualizar Información Personal",
            "Soporte y Reclamos"
        };

        for (String label : buttonLabels) {
            JButton button = new JButton(label);
            button.setFocusable(true);
            button.getAccessibleContext().setAccessibleDescription("Abrir " + label);
            button.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    openCorrespondingFrame(label);
                }
            });
            centerPanel.add(button);
        }

        getContentPane().add(centerPanel, BorderLayout.CENTER);

        // Panel inferior con botones adicionales
        JPanel bottomPanel = new JPanel(new FlowLayout(FlowLayout.RIGHT));
        JButton logoutButton = new JButton("Cerrar Sesión");
        logoutButton.setFocusable(true);
        logoutButton.getAccessibleContext().setAccessibleDescription("Cerrar sesión y volver a la pantalla de inicio");
        logoutButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                int confirm = JOptionPane.showConfirmDialog(
                    MainFrame.this,
                    "¿Está seguro que desea cerrar sesión?",
                    "Confirmar Cierre de Sesión",
                    JOptionPane.YES_NO_OPTION
                );
                if (confirm == JOptionPane.YES_OPTION) {
                    SwingUtilities.invokeLater(() -> {
                        new LoginFrame().setVisible(true);
                        dispose();
                    });
                }
            }
        });
        bottomPanel.add(logoutButton);
        getContentPane().add(bottomPanel, BorderLayout.SOUTH);

        setLocationRelativeTo(null);
        pack();
    }// </editor-fold>                        

    private void openCorrespondingFrame(String label) {
        SwingUtilities.invokeLater(() -> {
            switch (label) {
                case "Pagar Administración":
                    new PagoP().setVisible(true);
                    break;
                case "Reservar Espacio Común":
                    new ReservarEspacioP().setVisible(true);
                    break;
                case "Ver Facturas":
                    new FacturasP().setVisible(true);
                    break;
                case "Ver Multas":
                    new MultasP().setVisible(true);
                    break;
                case "Actualizar Información Personal":
                    new InformacionP().setVisible(true);
                    break;
                case "Soporte y Reclamos":
                    new SoporteP().setVisible(true);
                    break;
                default:
                    JOptionPane.showMessageDialog(this, "Funcionalidad no implementada: " + label);
            }
        });
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    // End of variables declaration                   
}
