/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mavenproject1;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author maxto3161
 */
public class MultasP extends javax.swing.JFrame {

    private JTable finesTable;
    private JButton viewDetailsButton, payButton;

    /**
     * Creates new form MultasP
     */
    public MultasP() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
        setTitle("Multas");
        setSize(600, 400);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new BorderLayout());

        // Crear tabla de multas
        String[] columnNames = {"Fecha del Evento", "Descripción", "Valor", "Fecha Límite de Pago", "Estado de Pago"};
        Object[][] data = {
            {"2023-10-01", "Violación de Parqueadero", "$50", "2023-11-01", "Pendiente"},
            {"2023-09-15", "Ruido Excesivo", "$30", "2023-10-15", "Pagado"}
        };
        DefaultTableModel model = new DefaultTableModel(data, columnNames);
        finesTable = new JTable(model);
        JScrollPane scrollPane = new JScrollPane(finesTable);
        getContentPane().add(scrollPane, BorderLayout.CENTER);

        // Panel de botones
        JPanel buttonPanel = new JPanel();
        viewDetailsButton = new JButton("Ver Detalles");
        payButton = new JButton("Pagar");
        buttonPanel.add(viewDetailsButton);
        buttonPanel.add(payButton);
        getContentPane().add(buttonPanel, BorderLayout.SOUTH);

        viewDetailsButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                int selectedRow = finesTable.getSelectedRow();
                if (selectedRow != -1) {
                    String description = (String) finesTable.getValueAt(selectedRow, 1);
                    String amount = (String) finesTable.getValueAt(selectedRow, 2);
                    JOptionPane.showMessageDialog(MultasP.this,
                        "Detalles de la multa:\n" +
                        "Descripción: " + description + 
                        "\nMonto: " + amount);
                } else {
                    JOptionPane.showMessageDialog(MultasP.this, "Por favor, seleccione una multa.");
                }
            }
        });

        payButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                int selectedRow = finesTable.getSelectedRow();
                if (selectedRow != -1) {
                    String status = (String) finesTable.getValueAt(selectedRow, 4);
                    if ("Pendiente".equals(status)) {
                        finesTable.setValueAt("Pagado", selectedRow, 4);
                        JOptionPane.showMessageDialog(MultasP.this, "Pago procesado exitosamente.");
                    } else {
                        JOptionPane.showMessageDialog(MultasP.this, "Esta multa ya ha sido pagada.");
                    }
                } else {
                    JOptionPane.showMessageDialog(MultasP.this, "Por favor, seleccione una multa para pagar.");
                }
            }
        });

        pack();
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MultasP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MultasP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MultasP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MultasP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MultasP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    // End of variables declaration                   
}
