/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mavenproject1;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author maxto3161
 */
public class RegistroP extends javax.swing.JFrame {

    private JTextField userField, nameField, emailField;
    private JPasswordField passwordField, confirmPasswordField;
    private JComboBox<String> roleComboBox;
    private JButton registerButton, cancelButton;
    private JLabel messageLabel;

    /**
     * Creates new form RegistroP
     */
    public RegistroP() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
        setTitle("Hojas Secas - Registro");
        setSize(400, 350);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new GridBagLayout());
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.insets = new Insets(5, 5, 5, 5);
        gbc.fill = GridBagConstraints.HORIZONTAL;

        // Usuario
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.gridwidth = 1;
        gbc.anchor = GridBagConstraints.LINE_START;
        getContentPane().add(new JLabel("Usuario:"), gbc);

        userField = new JTextField(20);
        gbc.gridx = 1;
        gbc.gridy = 1;
        getContentPane().add(userField, gbc);

        // Contraseña
        gbc.gridx = 0;
        gbc.gridy = 2;
        getContentPane().add(new JLabel("Contraseña:"), gbc);

        passwordField = new JPasswordField(20);
        gbc.gridx = 1;
        gbc.gridy = 2;
        getContentPane().add(passwordField, gbc);

        // Confirmar Contraseña
        gbc.gridx = 0;
        gbc.gridy = 3;
        getContentPane().add(new JLabel("Confirmar Contraseña:"), gbc);

        confirmPasswordField = new JPasswordField(20);
        gbc.gridx = 1;
        gbc.gridy = 3;
        getContentPane().add(confirmPasswordField, gbc);

        // Nombre
        gbc.gridx = 0;
        gbc.gridy = 4;
        getContentPane().add(new JLabel("Nombre:"), gbc);

        nameField = new JTextField(20);
        gbc.gridx = 1;
        gbc.gridy = 4;
        getContentPane().add(nameField, gbc);

        // Email
        gbc.gridx = 0;
        gbc.gridy = 5;
        getContentPane().add(new JLabel("Email:"), gbc);

        emailField = new JTextField(20);
        gbc.gridx = 1;
        gbc.gridy = 5;
        getContentPane().add(emailField, gbc);

        // Cargo
        gbc.gridx = 0;
        gbc.gridy = 6;
        getContentPane().add(new JLabel("Cargo:"), gbc);

        String[] roles = {"Propietario", "Inquilino", "Administrador"};
        roleComboBox = new JComboBox<>(roles);
        gbc.gridx = 1;
        gbc.gridy = 6;
        getContentPane().add(roleComboBox, gbc);

        // Botones
        JPanel buttonPanel = new JPanel(new FlowLayout(FlowLayout.CENTER));
        registerButton = new JButton("Registrar");
        cancelButton = new JButton("Cancelar");
        buttonPanel.add(registerButton);
        buttonPanel.add(cancelButton);
        gbc.gridx = 0;
        gbc.gridy = 7;
        gbc.gridwidth = 2;
        getContentPane().add(buttonPanel, gbc);

        // Mensaje
        messageLabel = new JLabel("");
        messageLabel.setForeground(Color.RED);
        gbc.gridx = 0;
        gbc.gridy = 8;
        gbc.gridwidth = 2;
        getContentPane().add(messageLabel, gbc);

        registerButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (validateFields()) {
                    JOptionPane.showMessageDialog(RegistroP.this,
                            "Usuario registrado exitosamente",
                            "Registro Exitoso",
                            JOptionPane.INFORMATION_MESSAGE);
                    dispose();
                    new LoginFrame().setVisible(true);
                }
            }
        });

        cancelButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                dispose();
                new LoginFrame().setVisible(true);
            }
        });

        pack();
    }// </editor-fold>                        

    private boolean validateFields() {
        if (userField.getText().trim().isEmpty() ||
            new String(passwordField.getPassword()).trim().isEmpty() ||
            new String(confirmPasswordField.getPassword()).trim().isEmpty() ||
            nameField.getText().trim().isEmpty() ||
            emailField.getText().trim().isEmpty()) {
            messageLabel.setText("Todos los campos son obligatorios");
            return false;
        }

        if (!new String(passwordField.getPassword()).equals(new String(confirmPasswordField.getPassword()))) {
            messageLabel.setText("Las contraseñas no coinciden");
            return false;
        }

        if (!emailField.getText().contains("@")) {
            messageLabel.setText("El email no es válido");
            return false;
        }

        messageLabel.setText("");
        return true;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    // End of variables declaration                   
}
